[package]
name = "pathfind"
version = "0.1.0"
authors = ["Ken Reed <kenakioreed@gmail.com>"]
edition = "2018"


[dependencies]
pathfinding = "2.0"
bit-vec = "0.6"
rayon="*"
dists = "*"
dinotree = "*"
dinotree_alg="*"
duckduckgeo="*"
